# Generated by Django 5.2.1 on 2025-05-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
