# Generated by Django 5.2.1 on 2025-05-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('LEVE', 'leve'), ('MEDIA', 'media'), ('GRAVE', 'grave')], default='LEVE', max_length=8, verbose_name='tipo de ticket'),
        ),
    ]
